version: "3.0"
services:
  db-sanritsu:
    #platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  wordpress-sanritsu:
    #platform: linux/x86_64
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - db-sanritsu
    ports:
      - 8893:80
    environment:
      WORDPRESS_DB_HOST: db-sanritsu
      WORDPRESS_DB_NAME: test
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db-sanritsu
    ports:
      - 4044:80
    environment:
      PMA_HOST: db-sanritsu
      PMA_USER: test
      PMA_PASSWORD: test
